# DCOS params:
zookeeper: "{{ groups['masters'] | join(':2181,') }}:2181"

# mesos-agent specific
mesos_workers:
  windows:
    service_name:     "mesos-agent"
    homedir:          "C:\\dcos"
    bindir:           "C:\\dcos\\bin"
    workdir:          "C:\\dcos\\work"
    imagesdir:        "C:\\dcos\\images"
    logdir:           "C:\\dcos\\mesos-logs"

resources_ports: "{{ over_resources_ports | default('10000-34000') }}"
mesos_agent_restart_count: 99
mesos_agent_restart_interval: "PT1M" # every 1min
mesos_agent_restart_duration: "PT5M" # every 5mins
system_user: "Administrator"

# Packages location
bucket_name: "dcos-win.s3.amazonaws.com"
url_to_mesosbin: "http://{{ bucket_name }}/mesos-binaries.{{ dcos['version'] }}.zip"
