- name: Windows | Reboot the host
  win_reboot:
  listen: reboot the host

- name: Windows | Set MESOS Agent dependency on Docker service
  win_service:
    name: "{{ mesos_workers.windows.service_name }}"
    dependencies: [ 'docker' ]
    start_mode: auto
    state: stopped
  listen: set dependency and reboot the service

- name: Windows | Start MESOS agent service
  win_service:
    name: "{{ mesos_workers.windows.service_name }}"
    state: restarted
  listen: set dependency and reboot the service