- name: Windows | Reboot the host
  win_reboot:
  listen: reboot the host

- name: Windows | Start MESOS agent service
  win_service:
    name: "{{ mesos_workers.windows.service_name }}"
    start_mode: auto
    state: restarted
  listen: reboot the service