---
scenario:
  name: delegated_win_agent
driver:
  name: delegated
platforms:
  - name: bootstrap1-centos7
    image: ami-9887c6e7
    region: us-east-1
    instance_type: m5.large
    ssh_user: centos
    os_type: centos
    connection: ssh
    user_data: ""
    groups:
      - bootstraps
      - dcos
  - name: master1-centos7
    image: ami-9887c6e7
    region: us-east-1
    instance_type: m5.large
    ssh_user: centos
    os_type: centos
    connection: ssh
    user_data: ""
    groups:
      - masters
      - dcos
  - name: agent1-windows
    image: ami-0d4d13e98bfd744c9
    region: us-east-1
    instance_type: m5.large
    os_type: windows
    volume_size: 30
    ssh_port: 5986
    ssh_user: Administrator
    connection: winrm
    groups:
      - agents_windows
      - dcos

provisioner:
  name: ansible
  log: true
  connection_options:
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: kerberos
  playbooks:
    delegated:
      create: ../ec2/create.yml
      destroy: ../ec2/destroy.yml
    converge: ../ec2/same_version_config_update_1-12.yml
    prepare: ../ec2/install_1-12_upgrade_1-12_windows.yml
  config_options:
    defaults:
      hash_behaviour: merge
  env:
    ANSIBLE_ROLES_PATH: "../../roles/"
  inventory:
    links:
      group_vars: ../../group_vars/
  lint:
    name: ansible-lint
    enabled: True
lint:
  name: yamllint
  options:
    config-file: .yamllint.yml
